# Build Task Checker without npm (uses standalone esbuild.exe).
# Run from PowerShell:  .\build.ps1

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$Tools = Join-Path $Root "tools"
$EsbuildVer = "0.27.2"
$Esbuild = Join-Path $Tools "esbuild.exe"

if (-not (Test-Path $Esbuild)) {
    Write-Host "Downloading esbuild $EsbuildVer (@esbuild/win32-x64) ..."
    New-Item -ItemType Directory -Force -Path $Tools | Out-Null
    $tgz = Join-Path $env:TEMP "esbuild-win32-x64.tgz"
    $url = "https://registry.npmjs.org/@esbuild/win32-x64/-/win32-x64-${EsbuildVer}.tgz"
    Invoke-WebRequest -Uri $url -OutFile $tgz -UseBasicParsing
    $tar = Join-Path $env:SystemRoot "System32\tar.exe"
    & $tar -xzf $tgz -C $Tools
    Remove-Item $tgz -Force
    $extracted = Join-Path $Tools "package\esbuild.exe"
    if (Test-Path $extracted) {
        Move-Item -Force $extracted $Esbuild
        Remove-Item -Recurse -Force (Join-Path $Tools "package") -ErrorAction SilentlyContinue
    }
    if (-not (Test-Path $Esbuild)) {
        throw "esbuild.exe not found after extract (expected $Esbuild)"
    }
}

$outFile = Join-Path $Root "main.js"

# Local install destination inside the vault
$installDir = Join-Path $Root "..\..\ToDo\personal\.obsidian\plugins\my-task-checker"

$banner = @"
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"@

$externals = @(
    "obsidian", "electron",
    "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
    "@codemirror/language", "@codemirror/lint", "@codemirror/search",
    "@codemirror/state", "@codemirror/view",
    "@lezer/common", "@lezer/highlight", "@lezer/lr"
) | ForEach-Object { "--external:$_" }

Write-Host "Building -> $outFile"
Push-Location $Root
try {
    & $Esbuild "src/main.ts" --bundle --format=cjs --platform=browser --target=es2018 `
        --tree-shaking=true `
        --banner:js="$banner" `
        --outfile="$outFile" `
        @externals
    if ($LASTEXITCODE -ne 0) { throw "esbuild failed with exit $LASTEXITCODE" }

    # Install into the vault plugin folder
    New-Item -ItemType Directory -Force -Path $installDir | Out-Null
    Copy-Item -Force $outFile (Join-Path $installDir "main.js")
    Copy-Item -Force (Join-Path $Root "manifest.json") (Join-Path $installDir "manifest.json")
    Write-Host "Installed -> $installDir"
    Write-Host "Done. Reload Obsidian (toggle Task Checker off/on)."
}
finally {
    Pop-Location
}
